_BASE_RUN: ../../pool/run/training/finetune.yaml
_BASE_MODEL: ../../pool/backbone/s3dg.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: HMDB51
  CHECKPOINT_FILE_PATH: ""          # !!@2
  BATCH_SIZE: 64
  NUM_FOLDS: 30
TEST:
  ENABLE: true
  DATASET: HMDB51
  BATCH_SIZE: 64
DATA:
  ANNO_DIR: /root/qingzhiwu/qingzhiwu/dataset/hmdb51/anno/
  DATA_ROOT_DIR: /root/qingzhiwu/qingzhiwu/dataset/hmdb51/videos/
VIDEO:
  HEAD:
    NUM_CLASSES: 51
    DROPOUT_RATE: 0.
OPTIMIZER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  WARMUP_EPOCHS: 10
  WARMUP_START_LR: 0.00002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true

OSS:
  ENABLE: false

NUM_GPUS: 8
PAI: true
